lista = [1.5]
print(lista)
lista.append("C")
lista.append("Java")
print(lista)
print(lista[2])
lista.remove(1.5)
lista.append("C++")
lista.append("C#")
lista.append("Php")
print(lista)
lista.reverse()
print(lista)
lista.append(['Portugol', 'Python', 'Pascal', 'Cobol', 'Mysql', 'Oracle'])
print(lista)
lista.reverse()
print(lista)
print(lista.index('C'))
print(lista.count('C'))
print(lista[-6])
del lista[0]
del lista[0]
print(lista[:-1])
print(lista[::-1])
