string = 'Testando string'
print(string[:3])
print(string[3:])
print(string[-3:])
print(string[:-3])
print(string[3:6])
print(string[::-1])
print(string[::2])
print(string[1::2])
print(string)
print(string.upper())
print(string.lower())
print(string.capitalize())
print(string.title())
print(string.swapcase())
print(string.replace('a', 'o'))
print(string.split())
print(string.split('a'))
print(string.splitlines())
print('amo' in string)
print(len(string))
string = string.upper()
print(string)
